// AUTO-GENERATED by scripts/gen_filter_keys.js from
// screamingfrog1/sources/seo/spider/seoelements/SeoElementFilterKey.java
// Do not edit by hand — regenerate with `node scripts/gen_filter_keys.js`.
//
// This is `FilterKey::is_deprecated`. The enum itself and shared types live in `mod.rs`;
// each metadata method lives in its own submodule for readability.

use super::FilterKey;

impl FilterKey {
    /// True if the Java source lists this key in the DEPRECATED EnumSet.
    pub fn is_deprecated(&self) -> bool {
        matches!(
            self,
            Self::AccessibilityRuleAriaDeprecatedRole
                | Self::ValidationHighCarbonRatingDeprecated1
                | Self::ValidationHighCarbonRatingDeprecated2
                | Self::UrlGaTrackingParametersDeprecated1
                | Self::UrlGaTrackingParametersDeprecated2
                | Self::PagespeedLayoutShiftDeprecated
                | Self::PagespeedUnsizedImagesDeprecated
                | Self::PagespeedUsesWebpImagesDeprecated
                | Self::PagespeedUsesTextCompressionDeprecated
                | Self::PagespeedTimeToFirstByteDeprecated
                | Self::PagespeedRedirectsDeprecated
                | Self::PagespeedDomSizeDeprecated
                | Self::PagespeedFontDisplayDeprecated
                | Self::PagespeedUsesOptimizedImagesDeprecated
                | Self::PagespeedEfficientAnimatedContentDeprecated
                | Self::PagespeedUsesResponsiveImagesDeprecated
                | Self::PagespeedLegacyJavaScriptDeprecated
                | Self::PagespeedUsesRelPreconnectDeprecated
                | Self::PagespeedRenderBlockingResourcesDeprecated
                | Self::PagespeedUsesLongCacheTtlDeprecated
                | Self::PagespeedOffscreenImagesDeprecated
                | Self::PagespeedUsesRelPreloadDeprecated
                | Self::MobileViewportNotSetDeprecated
        )
    }
}
