// Parses SeoElementFilterKey.java and generates Rust code for:
//   - FilterKey enum (all variants)
//   - impl FilterKey: tab(), i18n_key(), filter_key_type(), severity()
// Usage: node scripts/gen_filter_keys.js > crates/core/src/filter_key.rs
const fs = require('fs');
const path = require('path');

const JAVA = 'C:/Users/User/Desktop/screamingfrog1/sources/seo/spider/seoelements/SeoElementFilterKey.java';
const raw = fs.readFileSync(JAVA, 'utf8');

// Enum entry:
//   NAME(id1377782850.TAB, bitPos, idx, "i18n.key", nullOrArg, FilterKeyType.TYPE, id706500854.SEVERITY),
//
// NB some entries have a non-null fifth arg (e.g. integer for watermark interpolation).
// We capture raw string for the fifth arg but ignore its structure.
const RX = /^\s+([A-Z][A-Z0-9_]*)\(id1377782850\.([A-Z_]+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*"([^"]+)"\s*,\s*([^,]+?)\s*,\s*FilterKeyType\.([A-Z_]+)\s*,\s*id706500854\.([A-Z]+)\s*\)\s*[,;]/gm;

const TABS = {
  JAVASCRIPT: 'JavaScript',
  H1: 'H1',
  H2: 'H2',
  INTERNAL: 'Internal',
  EXTERNAL: 'External',
  AMP: 'Amp',
  CANONICALS: 'Canonicals',
  CONTENT: 'Content',
  CUSTOM_EXTRACTION: 'CustomExtraction',
  CUSTOM_SEARCH: 'CustomSearch',
  CUSTOM_JAVASCRIPT: 'CustomJavaScript',
  DIRECTIVES: 'Directives',
  ANALYTICS: 'Analytics',
  SEARCH_CONSOLE: 'SearchConsole',
  HREFLANG: 'Hreflang',
  IMAGES: 'Images',
  LINK_METRICS: 'LinkMetrics',
  META_DESCRIPTION: 'MetaDescription',
  META_KEYWORDS: 'MetaKeywords',
  PAGE_SPEED: 'PageSpeed',
  PAGINATION: 'Pagination',
  RESPONSE_CODE: 'ResponseCode',
  SECURITY: 'Security',
  SITEMAPS: 'Sitemaps',
  STRUCTURED_DATA: 'StructuredData',
  PAGE_TITLES: 'PageTitles',
  URL: 'Url',
  PARITY: 'Parity',
  LINKS: 'Links',
  VALIDATION: 'Validation',
  MOBILE: 'Mobile',
  AI: 'Ai',
  ACCESSIBILITY: 'Accessibility',
  UNDEF: 'Undef',
};

const FILTER_KEY_TYPES = {
  NORMAL: 'Normal',
  POST_CRAWL_ANALYSIS: 'PostCrawlAnalysis',
  SPELLING_AND_GRAMMAR: 'SpellingAndGrammar',
};

// Convert SCREAMING_SNAKE to CamelCase for Rust variant.
// Known compounds are kept readable (JavaScript, HTML, CSS, URL, HTTP, etc.).
const COMPOUND = {
  JAVASCRIPT: 'JavaScript',
  HTML: 'Html',
  CSS: 'Css',
  URL: 'Url',
  URLS: 'Urls',
  HTTP: 'Http',
  HTTPS: 'Https',
  PDF: 'Pdf',
  XML: 'Xml',
  AMP: 'Amp',
  JSON: 'Json',
  RSS: 'Rss',
  API: 'Api',
  GZIP: 'Gzip',
  GA: 'Ga',
  GSC: 'Gsc',
  LCP: 'Lcp',
  FCP: 'Fcp',
  CLS: 'Cls',
  FID: 'Fid',
  TTI: 'Tti',
  TTFB: 'Ttfb',
  INP: 'Inp',
  TBT: 'Tbt',
  SEO: 'Seo',
  AI: 'Ai',
  UUID: 'Uuid',
  ARIA: 'Aria',
  AVIF: 'Avif',
  WEBP: 'Webp',
};
function toCamel(name) {
  return name
    .split('_')
    .map((p) => {
      if (!p) return '';
      if (COMPOUND[p]) return COMPOUND[p];
      if (/^[0-9]/.test(p)) return p;
      return p[0] + p.slice(1).toLowerCase();
    })
    .join('');
}

// Produce the serde snake case name (for on-disk + JSON keys).
// This is what the enum was already emitting before the port.
function toSnake(name) {
  return name.toLowerCase();
}

// Turn an i18n key into a human label: last segment, "_" → " ", Title Case.
// Special casing for "x_characters" / "x_pixels" → "X Characters".
function humanize(i18n) {
  const leaf = i18n.split('.').pop();
  return leaf
    .split('_')
    .map((w) => {
      if (w === 'x') return 'X';
      if (w.length <= 3 && w === w.toLowerCase()) {
        // common small words we want as-is (is, of, to, url, seo, ai)
        const keep = new Set(['is', 'of', 'to', 'in', 'on', 'at', 'by', 'or', 'as']);
        if (keep.has(w)) return w;
      }
      return w[0].toUpperCase() + w.slice(1);
    })
    .join(' ');
}

const entries = [];
let m;
while ((m = RX.exec(raw)) !== null) {
  const [, name, tab, bitPos, idx, i18n, _fifthArg, fkt, sev] = m;
  if (!TABS[tab]) {
    throw new Error(`Unknown tab: ${tab} in ${name}`);
  }
  const hasWatermark = _fifthArg.trim() !== 'null';
  entries.push({
    name,
    variant: toCamel(name),
    serde: toSnake(name),
    tab,
    tabRust: TABS[tab],
    bitPos: Number(bitPos),
    idx: Number(idx),
    i18n,
    fkt,
    fktRust: FILTER_KEY_TYPES[fkt],
    sev,
    severity: sev === 'ISSUE' ? 'Issue' : 'Stat',
    hasWatermark,
    displayName: humanize(i18n),
  });
}

if (entries.length < 1000) {
  throw new Error(`Only parsed ${entries.length} entries — regex broke`);
}

// Verify unique variant names (CamelCase collisions).
const seen = new Set();
for (const e of entries) {
  if (seen.has(e.variant)) throw new Error(`Duplicate variant: ${e.variant}`);
  seen.add(e.variant);
}

// Group per tab for the for_tab() helper.
const byTab = {};
for (const e of entries) {
  (byTab[e.tab] ||= []).push(e);
}

// ---- Emit Rust ----
let out = '';
out += `// AUTO-GENERATED by scripts/gen_filter_keys.js from\n`;
out += `// screamingfrog1/sources/seo/spider/seoelements/SeoElementFilterKey.java\n`;
out += `// Do not edit by hand — regenerate with \`node scripts/gen_filter_keys.js\`.\n\n`;
out += `#![allow(clippy::too_many_lines)]\n\n`;
out += `use serde::{Deserialize, Serialize};\n\n`;
out += `use crate::tab::TabKey;\n\n`;

// FilterKeyType
out += `/// Classification of how a filter is evaluated.\n`;
out += `#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n`;
out += `#[serde(rename_all = "snake_case")]\n`;
out += `pub enum FilterKeyType {\n`;
out += `    Normal,\n`;
out += `    PostCrawlAnalysis,\n`;
out += `    SpellingAndGrammar,\n`;
out += `}\n\n`;

// Severity
out += `/// STAT = informational counter; ISSUE = flagged problem.\n`;
out += `#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n`;
out += `#[serde(rename_all = "snake_case")]\n`;
out += `pub enum FilterSeverity {\n`;
out += `    Stat,\n`;
out += `    Issue,\n`;
out += `}\n\n`;

// FilterKey enum
out += `/// Every filter shown in the UI, across all 33 tabs.\n`;
out += `///\n`;
out += `/// Ported from Java enum \`seo.spider.seoelements.SeoElementFilterKey\`.\n`;
out += `/// ${entries.length} variants — includes deprecated keys (kept for on-disk\n`;
out += `/// compatibility) marked via \`is_deprecated()\`.\n`;
out += `#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n`;
out += `#[serde(rename_all = "snake_case")]\n`;
out += `pub enum FilterKey {\n`;
for (const e of entries) {
  out += `    ${e.variant},\n`;
}
out += `}\n\n`;

// impl FilterKey
out += `impl FilterKey {\n`;

// tab()
out += `    /// Which UI tab this filter belongs to.\n`;
out += `    pub fn tab(&self) -> TabKey {\n`;
out += `        match self {\n`;
for (const e of entries) {
  out += `            Self::${e.variant} => TabKey::${e.tabRust},\n`;
}
out += `        }\n`;
out += `    }\n\n`;

// i18n_key()
out += `    /// i18n key for the filter's display name (e.g. "tab.internal.filter.html").\n`;
out += `    pub fn i18n_key(&self) -> &'static str {\n`;
out += `        match self {\n`;
for (const e of entries) {
  out += `            Self::${e.variant} => "${e.i18n}",\n`;
}
out += `        }\n`;
out += `    }\n\n`;

// filter_key_type()
out += `    /// NORMAL (evaluated online) / POST_CRAWL_ANALYSIS / SPELLING_AND_GRAMMAR.\n`;
out += `    pub fn filter_key_type(&self) -> FilterKeyType {\n`;
out += `        match self {\n`;
for (const e of entries) {
  out += `            Self::${e.variant} => FilterKeyType::${e.fktRust},\n`;
}
out += `        }\n`;
out += `    }\n\n`;

// severity()
out += `    /// STAT = counter, ISSUE = flagged problem.\n`;
out += `    pub fn severity(&self) -> FilterSeverity {\n`;
out += `        match self {\n`;
for (const e of entries) {
  out += `            Self::${e.variant} => FilterSeverity::${e.severity},\n`;
}
out += `        }\n`;
out += `    }\n\n`;

// bit_pos()
out += `    /// Internal bit position used by SF's on-disk format (kept for migration fidelity).\n`;
out += `    pub fn bit_pos(&self) -> i32 {\n`;
out += `        match self {\n`;
for (const e of entries) {
  out += `            Self::${e.variant} => ${e.bitPos},\n`;
}
out += `        }\n`;
out += `    }\n\n`;

// display_name()
out += `    /// Human-readable label derived from the i18n key's leaf segment.\n`;
out += `    pub fn display_name(&self) -> &'static str {\n`;
out += `        match self {\n`;
for (const e of entries) {
  out += `            Self::${e.variant} => "${e.displayName}",\n`;
}
out += `        }\n`;
out += `    }\n\n`;

// has_watermark()
out += `    /// True when the i18n template takes a configurable threshold (e.g. "over X characters").\n`;
out += `    pub fn has_watermark(&self) -> bool {\n`;
out += `        match self {\n`;
for (const e of entries) {
  out += `            Self::${e.variant} => ${e.hasWatermark ? 'true' : 'false'},\n`;
}
out += `        }\n`;
out += `    }\n\n`;

// is_deprecated()
out += `    /// True if the Java side lists this key in the DEPRECATED EnumSet.\n`;
out += `    /// Deprecated keys are kept for backward compatibility with older\n`;
out += `    /// crawl files but are never written by new crawls.\n`;
out += `    pub fn is_deprecated(&self) -> bool {\n`;
out += `        matches!(\n`;
out += `            self,\n`;
const deprecated = entries.filter((e) => /_DEPRECATED($|_)/.test(e.name));
out += deprecated.map((e) => `            Self::${e.variant}`).join(' |\n') + '\n';
out += `        )\n`;
out += `    }\n\n`;

// all()
out += `    /// Iterator over every filter key (including deprecated).\n`;
out += `    pub fn all() -> &'static [FilterKey] {\n`;
out += `        &[\n`;
for (const e of entries) {
  out += `            Self::${e.variant},\n`;
}
out += `        ]\n`;
out += `    }\n\n`;

// for_tab()
out += `    /// All filter keys belonging to a given tab, in declaration order.\n`;
out += `    pub fn for_tab(tab: TabKey) -> Vec<FilterKey> {\n`;
out += `        Self::all().iter().copied().filter(|k| k.tab() == tab).collect()\n`;
out += `    }\n`;

out += `}\n`;

process.stdout.write(out);

// Report to stderr so stdout is pure Rust.
const perTab = Object.fromEntries(
  Object.entries(byTab).map(([k, v]) => [k, v.length])
);
process.stderr.write(
  `Parsed ${entries.length} filter keys across ${Object.keys(byTab).length} tabs\n` +
    `Per-tab counts:\n` +
    Object.entries(perTab)
      .sort((a, b) => b[1] - a[1])
      .map(([k, v]) => `  ${k.padEnd(20)} ${v}`)
      .join('\n') +
    '\n' +
    `Deprecated: ${deprecated.length}\n`
);
